name: Acceptance

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Test on PHP ${{ matrix.php-version }}
    strategy:
      matrix:
        php-version:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: pdo, pdo-sqlite
        coverage: none
    - name: Dependencies
      run: make deps-install
    - name: Test
      run: make test

  cs-check:
    runs-on: ubuntu-latest
    name: Code standard
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up PHP 8.0
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        coverage: none
    - name: Composer
      run: make deps-install
    - name: Code standard
      run: make cs-check

  coverage:
    runs-on: ubuntu-latest
    name: Code coverage
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up PHP 8.0
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        coverage: xdebug
    - name: Composer
      run: make deps-install
    - name: Code coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make coverage
